### ISSUE TITLE
Hello! I need your help!!!

### ISSUE THREAD

**Issue by Zavkiell** [BadgerCode/BadgerCode#1]
I’m your follower in GitHub and I need your help in Garry’s mod. So, how to make 2d nextbots big? It’s the new folder steam/steamapps/workshop/content/4000. I found the nextbot I need but how to change a sprite_size from 128 to 1000???

**Comment by BadgerCode** [comment]
Hello!

I'm not familiar with the 2D nextbots code I'm afraid.

Are you using a specific workshop addon?
Maybe the addon creator could help you?
Or you could leave a comment/create a discussion on the workshop addon
